/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Sebas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        initCustom();
    }

    private void initCustom() {
        setTitle("Login");
        setSize(400, 220);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new java.awt.BorderLayout());

        javax.swing.JPanel center = new javax.swing.JPanel(new java.awt.GridLayout(3,2,8,8));
        javax.swing.JLabel lblUser = new javax.swing.JLabel("Usuario:");
        javax.swing.JTextField tfUser = new javax.swing.JTextField();
        javax.swing.JLabel lblPass = new javax.swing.JLabel("Contraseña:");
        javax.swing.JPasswordField pf = new javax.swing.JPasswordField();

        center.setBorder(javax.swing.BorderFactory.createEmptyBorder(12,12,12,12));
        center.add(lblUser); center.add(tfUser);
        center.add(lblPass); center.add(pf);

        javax.swing.JButton btnLogin = new javax.swing.JButton("Iniciar sesión");
        javax.swing.JButton btnCancelar = new javax.swing.JButton("Cancelar");

        javax.swing.JPanel bottom = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        bottom.add(btnCancelar); bottom.add(btnLogin);

        add(center, java.awt.BorderLayout.CENTER);
        add(bottom, java.awt.BorderLayout.SOUTH);

        btnCancelar.addActionListener(e -> System.exit(0));

        btnLogin.addActionListener(e -> {
            String user = tfUser.getText().trim();
            String pass = new String(pf.getPassword());
            if (user.isEmpty() || pass.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña");
                return;
            }
            CRUD.UsuarioCRUD ucrud = new CRUD.UsuarioCRUD();
            Clases.Usuario u = ucrud.login(user, pass);
            if (u != null) {
                // abrir ventana principal según rol
                VentanaPrincipal vp = new VentanaPrincipal(u);
                vp.setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario/contraseña incorrectos");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
